backend:
  name: github
  branch: prod-yoco
  repo: fntechgit/virtualevent-poc
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "configurations"
    label: "Configurations"
    editor:
      preview: false
    files:
      - file: "src/content/ads.json"
        label: "Advertisement"
        name: "ads"
        fields:
          - {label: "Ads", name: "ads", widget: list, fields: [
              {label: "Page", name: "section", widget: string},
              {label: "Columns", name: "columns", widget: list, fields: [
                {label: "Column", name: "column", widget: select, options: [
                  { label: "Left", value: "left" },
                  { label: "Center", value: "center" },
                  { label: "Right", value: "right" },
                ]},
                {label: "Ads", name: "columnAds", widget: list, required: false, fields: [
                  {label: "Image", name: "image", widget: image},
                  {label: "Button", name: button, widget: object, required: false, fields: [
                    {label: "Text", name: "text", widget: string, required: false},
                    {label: "Link", name: "link", widget: string, required: false}
                  ]},
                  {label: "Specific Event?", name: "id", widget: string, required: false}
                ]}
              ]},
            ]}
      - file: "src/content/sponsor.json"
        label: "Sponsors"
        name: "sponsor"
        fields:
          - {label: "Sponsors", name: "sponsors", widget: object, fields: [
              {label: "Gold Tier", name: "gold", widget: object, fields: [
                {label: "Sponsors", name: "sponsors", widget: list, fields: [
                  {label: "Name", name: "name", widget: string },
                  {label: "Image", name: "image", widget: image }
                ]},
                {label: "Button", name: button, widget: object, fields: [
                  {label: "Text", name: "text", widget: string, required: false},
                  {label: "Link", name: "link", widget: string, required: false}
                ]}
              ]},
              {label: "Silver Tier", name: "silver", widget: object, fields: [
                {label: "Sponsors", name: "sponsors", widget: list, fields: [
                  {label: "Name", name: "name", widget: string },
                  {label: "Image", name: "image", widget: image }
                ]},
                {label: "Button", name: button, widget: object, fields: [
                  {label: "Text", name: "text", widget: string, required: false},
                  {label: "Link", name: "link", widget: string, required: false}
                ]}
              ]},
            ]}
      - file: "src/content/navbar.json"
        label: "Navbar"
        name: "navbar"
        fields:
          - {label: "Navbar", name: "items", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Link", name: "link", widget: string},
              {label: "Display", name: "display", widget: boolean, required: false},
            ]}
      - file: "src/content/footer.json"
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Columns", name: "columns", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Display", name: "display", widget: boolean, required: false},
              {label: "Items", name: "items", widget: list, fields: [
                {label: "Title", name: "title", widget: string},
                {label: "Link", name: "link", widget: string},         
              ]}
            ]}
          - {label: "Logo", name: "logo", widget: object, fields: [
              {label: "Display", name: "display", widget: boolean, required: false},
            ]}
          - {label: "Social", name: "social", widget: object, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Display", name: "display", widget: boolean, required: false},
              {label: "Networks", name: "networks", widget: list, fields: [
                {label: "Icon", name: "icon", widget: string},
                {label: "Link", name: "link", widget: string},
                {label: "Display", name: "display", widget: boolean, required: false},
              ]}
            ]}
          - {label: "Legal", name: "legal", widget: list, fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Link", name: "link", widget: string},         
            ]}
  - name: "home"
    label: "Lobby Site"
    editor:
      preview: false
    files:
      - file: "src/content/home-settings.json"
        name: "homeSettings"
        label: "Lobby Settings"
        fields:
          - {label: "Center Column", name: "centerColumn", widget: object, fields: [
              {label: "Schedule", name: "schedule", widget: object, fields: [
                {label: "Show all events", name: "showAllEvents", widget: boolean, required: false}
              ]}
            ]}
  - name: "marketing"
    label: "Marketing Site"
    editor:
      preview: false
    files:
      - file: "src/content/marketing-site.json"
        name: "marketingSite"
        label: "Marketing Site"
        fields:
          - {label: "Hero Banner", name: "heroBanner", widget: "object", fields: [
              {label: "Title", name: "title", widget: string},
              {label: "Sub Title", name: "subTitle", widget: string, required: false},
              {label: "Date", name: "date", widget: string, required: false},
              {label: "Date Layout", name: "dateLayout", widget: boolean, required: false},
              {label: "Time", name: "time", widget: string, required: false},
              {label: "Buttons", name: "buttons", widget: object, fields: [
                {label: "Register Button", name: "registerButton", widget: object, fields: [
                  {label: "Text", name: "text", widget: string},
                  {label: "Display", name: "display", widget: boolean, required: false},
                ]},
                {label: "Login Button", name: "loginButton", widget: object, fields: [
                  {label: "Text", name: "text", widget: string},
                  {label: "Display", name: "display", widget: boolean, required: false},
                ]}                
              ]},
              {label: "Background Image", name: "background", widget: image, required: false},
              {label: "Images", name: "images", widget: list, fields: [
                {label: "Image", name: "image", widget: image}
              ]},
            ]}
          - {label: "Widgets", name: "leftColumn", widget: object, fields: [
              {label: "Schedule", name: "schedule", widget: boolean, required: false},
              {label: "Disqus", name: "disqus", widget: boolean, required: false},
            ]}
          - {label: "Sponsors", name: "sponsors", widget: list, fields: [
              {label: "Image", name: "image", widget: image, required: false},
              {label: "Size", name: "size", widget: hidden}
            ]}
  - name: "virtualBooth"
    label: "Virtual Booth"
    files: 
      - file: "src/pages/virtual-booth.md"
        name: "virtualBoothPage"
        label: "Virtual Booth Page"      
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "virtual-booth-page"}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Columns, name: columns, widget: object, fields: [
              {label: Left Column, name: leftColumn, widget: object, fields: [
                {label: Title, name: title, widget: string},
                {label: Content, name: content, widget: text},
                {label: Image, name: image, widget: image}
              ]},
              {label: Right Column, name: rightColumn, widget: object, fields: [
                {label: Title, name: title, widget: string},
                {label: Content, name: content, widget: text},
                {label: Image, name: image, widget: image}
              ]}
            ]}
          - {label: End Text, name: endText, widget: markdown}
          - {label: "Body", name: body, widget: markdown}
  - name: "pages"
    label: "Pages"
    folder: "src/pages/custom-pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "custom-page"}
      - {label: Title, name: title, widget: string}
      - {label: "Body", name: body, widget: markdown}
